import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { apiClient } from "../apiClient";
export function CommunicationRailsCard({ selectedJobUid, onFeedback, }) {
    const [gmailTo, setGmailTo] = useState("connor@kharon.co.za");
    const [gmailSubject, setGmailSubject] = useState("Kharon service update");
    const [gmailBody, setGmailBody] = useState("Service team update attached.");
    const [chatMessage, setChatMessage] = useState("Dispatcher alert test");
    const [chatSeverity, setChatSeverity] = useState("info");
    const [personName, setPersonName] = useState("New Contact");
    const [personEmail, setPersonEmail] = useState("connor@kharon.co.za");
    const [personPhone, setPersonPhone] = useState("+27110000000");
    return (_jsxs("article", { className: "workspace-card", children: [_jsxs("div", { className: "panel-heading", children: [_jsx("p", { className: "panel-eyebrow", children: "Communication rails" }), _jsx("h2", { children: "Outbound actions" })] }), _jsxs("div", { className: "control-block", children: [_jsxs("div", { className: "control-block__head", children: [_jsx("h3", { children: "Gmail notify" }), _jsx("p", { children: "Send an update linked to the selected job." })] }), _jsxs("div", { className: "form-grid", children: [_jsxs("label", { className: "field-stack", children: [_jsx("span", { children: "To" }), _jsx("input", { name: "gmail_to", value: gmailTo, onChange: (event) => setGmailTo(event.target.value), placeholder: "to" })] }), _jsxs("label", { className: "field-stack", children: [_jsx("span", { children: "Subject" }), _jsx("input", { name: "gmail_subject", value: gmailSubject, onChange: (event) => setGmailSubject(event.target.value), placeholder: "subject" })] }), _jsxs("label", { className: "field-stack field-stack--full", children: [_jsx("span", { children: "Body" }), _jsx("input", { name: "gmail_body", value: gmailBody, onChange: (event) => setGmailBody(event.target.value), placeholder: "body" })] }), _jsxs("div", { className: "field-stack field-stack--action", children: [_jsx("span", { children: "\u00A0" }), _jsx("button", { className: "button button--secondary", onClick: async () => {
                                            await apiClient.sendGmailNotification(gmailTo, gmailSubject, gmailBody, selectedJobUid);
                                            onFeedback("Gmail notification sent.");
                                        }, children: "Send" })] })] })] }), _jsxs("div", { className: "control-block", children: [_jsxs("div", { className: "control-block__head", children: [_jsx("h3", { children: "Chat alert" }), _jsx("p", { children: "Escalate a dispatch message for the selected job." })] }), _jsxs("div", { className: "button-row", children: [_jsxs("select", { name: "chat_severity", value: chatSeverity, onChange: (event) => setChatSeverity(event.target.value), children: [_jsx("option", { value: "info", children: "info" }), _jsx("option", { value: "warning", children: "warning" }), _jsx("option", { value: "critical", children: "critical" })] }), _jsx("input", { name: "chat_message", value: chatMessage, onChange: (event) => setChatMessage(event.target.value), placeholder: "message" }), _jsx("button", { className: "button button--secondary", onClick: async () => {
                                    await apiClient.sendChatAlert(chatMessage, chatSeverity, selectedJobUid);
                                    onFeedback("Chat alert sent.");
                                }, children: "Alert" })] })] }), _jsxs("div", { className: "control-block", children: [_jsxs("div", { className: "control-block__head", children: [_jsx("h3", { children: "People sync" }), _jsx("p", { children: "Push a contact update into the shared people surface." })] }), _jsxs("div", { className: "form-grid", children: [_jsxs("label", { className: "field-stack", children: [_jsx("span", { children: "Name" }), _jsx("input", { name: "person_name", value: personName, onChange: (event) => setPersonName(event.target.value), placeholder: "name" })] }), _jsxs("label", { className: "field-stack", children: [_jsx("span", { children: "Email" }), _jsx("input", { name: "person_email", value: personEmail, onChange: (event) => setPersonEmail(event.target.value), placeholder: "email" })] }), _jsxs("label", { className: "field-stack", children: [_jsx("span", { children: "Phone" }), _jsx("input", { name: "person_phone", value: personPhone, onChange: (event) => setPersonPhone(event.target.value), placeholder: "phone" })] }), _jsxs("div", { className: "field-stack field-stack--action", children: [_jsx("span", { children: "\u00A0" }), _jsx("button", { className: "button button--secondary", onClick: async () => {
                                            await apiClient.syncPerson(personName, personEmail, personPhone, "client");
                                            onFeedback("People sync executed.");
                                        }, children: "Sync" })] })] })] })] }));
}
