import { StyleSheet } from '@react-pdf/renderer';

export const COLORS = {
  brand: '#581c87',
  brandSoft: '#f3e8ff',
  action: '#1d4ed8',
  surface: '#f8fafc',
  border: '#e2e8f0',
  muted: '#64748b',
  text: '#0f172a',
  white: '#ffffff',
};

export const SERVICE_PROVIDER = {
  name: 'KharonOps',
  descriptor: 'Fire & Security Compliance Platform',
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: COLORS.text,
    backgroundColor: COLORS.white,
    paddingTop: 28,
    paddingRight: 30,
    paddingBottom: 42,
    paddingLeft: 30,
    lineHeight: 1.35,
  },
  pageA5: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: COLORS.text,
    backgroundColor: COLORS.white,
    paddingTop: 18,
    paddingRight: 18,
    paddingBottom: 22,
    paddingLeft: 18,
    lineHeight: 1.3,
  },
  headerBand: {
    backgroundColor: COLORS.brand,
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 10,
    paddingLeft: 12,
    borderRadius: 4,
    marginBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 14,
    color: COLORS.white,
    letterSpacing: 0.6,
  },
  headerSubtitle: {
    fontSize: 8,
    color: COLORS.brandSoft,
    marginTop: 3,
  },
  headerMetaBlock: {
    alignItems: 'flex-end',
  },
  headerMetaText: {
    fontSize: 8,
    color: COLORS.white,
    marginBottom: 2,
  },
  reportTopMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    borderRadius: 4,
  },
  reportTopMetaItem: {
    width: '33.333%',
    marginBottom: 4,
    paddingRight: 8,
  },
  a5TopMetaItem: {
    width: '50%',
    marginBottom: 4,
    paddingRight: 6,
  },
  microLabel: {
    fontSize: 6.8,
    color: COLORS.muted,
    marginBottom: 1,
    fontFamily: 'Helvetica-Bold',
  },
  microValue: {
    fontSize: 8.2,
    color: COLORS.text,
  },
  section: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    marginBottom: 10,
    borderRadius: 4,
  },
  sectionHeader: {
    backgroundColor: COLORS.brandSoft,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingTop: 6,
    paddingRight: 10,
    paddingBottom: 6,
    paddingLeft: 10,
  },
  sectionTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9.5,
    color: COLORS.brand,
    letterSpacing: 0.3,
  },
  sectionBody: {
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  infoCellHalf: {
    width: '50%',
    paddingRight: 8,
    marginBottom: 7,
  },
  infoCellThird: {
    width: '33.333%',
    paddingRight: 8,
    marginBottom: 7,
  },
  infoCellQuarter: {
    width: '25%',
    paddingRight: 8,
    marginBottom: 7,
  },
  infoLabel: {
    fontSize: 7,
    color: COLORS.muted,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 9,
    color: COLORS.text,
  },
  bodyText: {
    fontSize: 9,
    color: COLORS.text,
  },
  emphasisText: {
    fontFamily: 'Helvetica-Bold',
  },
  noteBox: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
  },
  table: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: COLORS.brandSoft,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingTop: 7,
    paddingRight: 8,
    paddingBottom: 7,
    paddingLeft: 8,
  },
  tableRow: {
    flexDirection: 'row',
    paddingTop: 7,
    paddingRight: 8,
    paddingBottom: 7,
    paddingLeft: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tableRowAlt: {
    backgroundColor: COLORS.surface,
  },
  tableLastRow: {
    borderBottomWidth: 0,
  },
  colTask: {
    width: '49%',
    paddingRight: 8,
  },
  colStatus: {
    width: '9%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colValue: {
    width: '24%',
    paddingLeft: 6,
  },
  taskText: {
    fontSize: 8.6,
    color: COLORS.text,
  },
  headerCellText: {
    fontSize: 7.5,
    color: COLORS.brand,
    fontFamily: 'Helvetica-Bold',
  },
  statusCell: {
    width: 22,
    height: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3,
    backgroundColor: COLORS.white,
  },
  statusCellPass: {
    backgroundColor: COLORS.brandSoft,
    borderColor: COLORS.brand,
  },
  statusCellFail: {
    backgroundColor: '#dbeafe',
    borderColor: COLORS.action,
  },
  statusCellNa: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.muted,
  },
  statusCellText: {
    fontSize: 7.5,
    color: COLORS.text,
    fontFamily: 'Helvetica-Bold',
  },
  defectCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    backgroundColor: COLORS.surface,
    paddingTop: 8,
    paddingRight: 9,
    paddingBottom: 8,
    paddingLeft: 9,
    marginBottom: 7,
  },
  defectHeading: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
    color: COLORS.brand,
    marginBottom: 4,
  },
  defectLine: {
    fontSize: 8.6,
    color: COLORS.text,
    marginBottom: 2,
  },
  signatureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  signaturePanel: {
    width: '48.5%',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingTop: 9,
    paddingRight: 10,
    paddingBottom: 9,
    paddingLeft: 10,
    minHeight: 98,
  },
  signaturePanelTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 8.5,
    color: COLORS.brand,
    marginBottom: 7,
  },
  signatureImageWrap: {
    height: 34,
    justifyContent: 'center',
    marginBottom: 6,
  },
  signatureImage: {
    width: 120,
    height: 34,
  },
  signaturePlaceholder: {
    width: 120,
    height: 34,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.text,
    justifyContent: 'flex-end',
  },
  signaturePlaceholderText: {
    fontSize: 7,
    color: COLORS.muted,
  },
  signatureMeta: {
    fontSize: 8.2,
    marginBottom: 2,
    color: COLORS.text,
  },
  clientSignLine: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.text,
    marginTop: 18,
    marginBottom: 6,
  },
  clientSignHint: {
    fontSize: 7.2,
    color: COLORS.muted,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 16,
    right: 30,
    fontSize: 8,
    color: COLORS.muted,
  },
  certificateOuter: {
    flex: 1,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: COLORS.text,
    paddingTop: 8,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
  },
  certificateInner: {
    flex: 1,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: COLORS.text,
    paddingTop: 26,
    paddingRight: 26,
    paddingBottom: 22,
    paddingLeft: 26,
    justifyContent: 'space-between',
  },
  certificateIssuer: {
    textAlign: 'center',
    fontSize: 8.5,
    color: COLORS.muted,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  certificateTitle: {
    fontFamily: 'Times-Bold',
    textAlign: 'center',
    fontSize: 19,
    color: COLORS.text,
    marginBottom: 12,
  },
  certificateRefRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  certificateRefBox: {
    width: '48.5%',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    borderRadius: 4,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
  },
  certificateBanner: {
    backgroundColor: COLORS.brandSoft,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
    marginBottom: 14,
  },
  certificateBannerText: {
    textAlign: 'center',
    color: COLORS.brand,
    fontFamily: 'Helvetica-Bold',
    fontSize: 11,
    letterSpacing: 0.4,
  },
  certificateParagraph: {
    fontSize: 10,
    color: COLORS.text,
    textAlign: 'justify',
    marginBottom: 10,
    lineHeight: 1.45,
  },
  certificateDeclaration: {
    fontSize: 10,
    color: COLORS.text,
    marginBottom: 12,
    fontFamily: 'Helvetica-Bold',
  },
  certificateStatusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  certificateStatusCard: {
    width: '50%',
    paddingRight: 8,
    marginBottom: 8,
  },
  certificateStatusInner: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    backgroundColor: COLORS.surface,
    paddingTop: 8,
    paddingRight: 10,
    paddingBottom: 8,
    paddingLeft: 10,
  },
  certificateHash: {
    textAlign: 'center',
    fontSize: 8.2,
    color: COLORS.muted,
    marginTop: 12,
  },
  spacer: {
    marginBottom: 8,
  },
});
